### ISSUE TITLE
Default log_dir '/home/{user}' for monitored is not quite good.

### ISSUE THREAD

**Issue by lizhenda** [pingcap-incubator/tiup-cluster#356]
My topology yaml is as follow. Then the log dir for blackbox_exporter/node_exporter will be set to '/home/tidb'.  I think '{deploy_dir}/logs' for the default log dir here will be a better choice.

`
# Tip: PD priority needs to be manually set using the PD-ctl client tool. such as, member Leader_priority PD-name numbers.
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/data/tidb/"
  #data_dir: ""
  #log_dir: ""
#monitored:
#  node_exporter_port: 9100
#  blackbox_exporter_port: 9115
#  deploy_dir: ""
#  data_dir: ""
#  log_dir: ""
`

**Comment by AstroProfundis** [comment]
Thank  you for the advice.

The `monitor-xxx` path will only be present on monitoring node (where prometheus and grafana are deployed), but `*_exporter`s are deployed to every deploy host, so it's not really suitable for them to be under a `monitor-xxx` sub path.

You can set `log_dir` in the topology file's `global` section to give them a more accurate location. If the value of `log_dir` is a relative path, it will be a sub directory under `/home/{user}`, and if it's a absolute one, it will be relative to `/`.

**Comment by lizhenda** [comment]
@AstroProfundis 
I set `log_dir` in the `global` section in a relative way, but it doesn't work. 

run scripts still log to `/home/{user}`.
```shell
$ grep -rnI log /data/tidb/monitor-9100/
/data/tidb/monitor-9100/scripts/run_blackbox_exporter.sh:9:exec > >(tee -i -a "/home/tidb/blackbox_exporter.log")
/data/tidb/monitor-9100/scripts/run_blackbox_exporter.sh:13:    --log.level="info" \
/data/tidb/monitor-9100/scripts/run_node_exporter.sh:9:exec > >(tee -i -a "/home/tidb/node_exporter.log")
/data/tidb/monitor-9100/scripts/run_node_exporter.sh:19:    --log.level="info"
```

Topology file is as follow.
```yaml
global:
  deploy_dir: /data/tidb
  log_dir: logs
  user: tidb
monitored:
  node_exporter_port: 9100
  blackbox_exporter_port: 9115
server_configs:
  pd:
    replication.location-labels:
    - region
    - az
    - rack
    - host
tidb_servers:
- host: 192.168.56.101
  ssh_port: 22
  port: 4000
  status_port: 10080
tikv_servers:
- host: 192.168.56.101
  ssh_port: 22
  port: 20160
  status_port: 20180
  config:
    server.labels:
      region: nm
      az: nm4
      rack: rack1
      host: 192.168.56.101_20160
- host: 192.168.56.101
  ssh_port: 22
  port: 20161
  status_port: 20181
  config:
    server.labels:
      region: nm
      az: nm4
      rack: rack1
      host: 192.168.56.101_20161
- host: 192.168.56.101
  ssh_port: 22
  port: 20162
  status_port: 20182
  config:
    server.labels:
      region: nm
      az: nm4
      rack: rack1
      host: 192.168.56.101_20162
pd_servers:
- host: 192.168.56.101
  ssh_port: 22
  client_port: 2379
  peer_port: 2380
monitoring_servers:
- host: 192.168.56.101
  ssh_port: 22
grafana_servers:
- host: 192.168.56.101
  ssh_port: 22
```
